apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: myapp
spec:
  replicas: 3
  template:
    metadata:
      name: myapp-rc
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx-container
          image: nginx


#kubectl create -f demo.replicaController.yaml
#kubectl get replicationcontroller
