apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myreplicaset
  labels:
    app: myapp
    type: front-end
spec:
  replicas: 3
  selector:
    matchLabels:
      type: front-end
  template:
    metadata:
      labels:
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx

# kubectl create -f demo.replicaset.yaml
# kubectl get replicaset
# kubectl scale --replicas=6 -f demo.replicaset.yaml
# kubectl scale --replicas=6 replicaset myapp-replicaset

# kubectl delete replicaset myapp-replicaset
# kubectl replace -f replicaset-definition.yaml
# kubectl scale -replicas=6 -f replicaset-definition.yaml

# kubectl edit replicaset myapp-replicaset

