apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
    - name: nginx-container
      image: nginx

# kubectl create -f pod-defination.yaml
#kubectl get pods
#kubectl describe pod myapp-pod