apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    type: front-end
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080

#kubectl port-forward svc/nginx-service 8080:80
